[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[functions]
  # Next.js server functions
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-nextjs" 